name: CI/CD Pipeline with Approval Gate

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Security Scan (Bandit)
        run: bandit -r .

      - name: Run Python Script (Staging)
        run: python app.py

  approve-and-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com  # Placeholder for real deployment URL
    steps:
      - name: Deploy to Production
        run: echo "🚀 Deploying to production!"
